os: osx
osx_image: xcode10.2
language: java
jdk:
  - oraclejdk12
sudo: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew clean assemble
  - ./gradlew podspec
  - ./gradlew clean test :app-spring:bootJar
  - ./gradlew publishToMavenLocal
  - cd ./app-quarkus
  - ./mvnw package