os: osx
osx_image: xcode11
language: java
jdk:
  - oraclejdk12
sudo: false
before_cache:
  - rm -rf $HOME/.m2/repository/name/antonsmirnov/
cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/
    - $HOME/.konan/
script:
  - ./gradlew clean assemble
  - ./gradlew podspec
  - ./gradlew clean test :app-spring:bootJar
  - ./gradlew publishToMavenLocal
  - ./mvnw package -f app-quarkus/pom.xml
  - ./mvnw package -f app-spring-vaadin/pom.xml